-- Données Fest-noz Vras Kalanna 2026 (exportées de la version claude.ai)
BEGIN;
INSERT INTO events (id,nom,lieu,debut,fin,sheet_url,image_url,contact,deroule) VALUES ('kalanna26','Fest-noz Vras Kalanna 2026','Quimper','2026-12-29','2027-01-02','https://docs.google.com/spreadsheets/d/1HvRV86lsLdmffUkXGuyAQl45E9FklPDL/edit?gid=139294156#gid=139294156','https://ik.imagekit.io/hfctelrlt/2026/kalanna2026-web.png','degemer@kalanna.bzh','19:00 Apéro
20:00 Ouverture des portes
04:15 Fin de la musique
04:45 Fin du service bar
06:00 Départ des derniers bénévoles');
INSERT INTO postes (id,event_id,nom,couleur,responsable,description) VALUES ('billet','kalanna26','Bilhederezh – Billetterie',2,NULL,'Caisse et contrôle des entrées. Après 1h : caisse crêpes/gâteaux.');
INSERT INTO postes (id,event_id,nom,couleur,responsable,description) VALUES ('bod','kalanna26','Bod – Hébergement artistes & techniciens',3,NULL,'Point hébergement Ti ar Brug : préparation des chambres, petit-déjeuner, ménage, linge (28 draps…).');
INSERT INTO postes (id,event_id,nom,couleur,responsable,description) VALUES ('bugale','kalanna26','Korn ar vugale – Espace enfants',5,NULL,NULL);
INSERT INTO postes (id,event_id,nom,couleur,responsable,description) VALUES ('caisses','kalanna26','Suivi des caisses',4,NULL,'Trésorier + aide, toute la soirée.');
INSERT INTO postes (id,event_id,nom,couleur,responsable,description) VALUES ('degemer','kalanna26','Degemer an dud – Accueil bénévoles',2,NULL,NULL);
INSERT INTO postes (id,event_id,nom,couleur,responsable,description) VALUES ('gobel','kalanna26','Gobelets',4,NULL,'Gestion des gobelets, 1 personne par créneau.');
INSERT INTO postes (id,event_id,nom,couleur,responsable,description) VALUES ('gwisk','kalanna26','Gwiskva – Vestiaire',6,NULL,'2 stands.');
INSERT INTO postes (id,event_id,nom,couleur,responsable,description) VALUES ('inst','kalanna26','Staliadur ha kempenn – Installation & rangement',0,NULL,'29/12 : matériel aux services techniques de Quimper, matelas Skol Diwan, point hébergement Ti ar Brug, préinstallation déco. 30/12 : tables, éclairage, déco. 02/01 : rangement et nettoyage.');
INSERT INTO postes (id,event_id,nom,couleur,responsable,description) VALUES ('kramp-enc','kalanna26','Krampouezh – Encaissement',1,NULL,NULL);
INSERT INTO postes (id,event_id,nom,couleur,responsable,description) VALUES ('kramp-garn','kalanna26','Krampouezh – Garnissage',1,NULL,NULL);
INSERT INTO postes (id,event_id,nom,couleur,responsable,description) VALUES ('kramp-prep','kalanna26','Krampouezh – Préparation (veille)',1,NULL,'Préparation de la pâte et des ingrédients la veille (Quimperlé).');
INSERT INTO postes (id,event_id,nom,couleur,responsable,description) VALUES ('kramp-rav','kalanna26','Krampouezh – Ravitaillement',1,NULL,NULL);
INSERT INTO postes (id,event_id,nom,couleur,responsable,description) VALUES ('kramp-resp','kalanna26','Krampouezh – Responsables',1,NULL,'1 stand côté cuisine, 14 billigs.');
INSERT INTO postes (id,event_id,nom,couleur,responsable,description) VALUES ('kramp-tour','kalanna26','Krampouezh – Tourneurs',1,NULL,NULL);
INSERT INTO postes (id,event_id,nom,couleur,responsable,description) VALUES ('kramp-vais','kalanna26','Krampouezh – Vaisselle',1,NULL,NULL);
INSERT INTO postes (id,event_id,nom,couleur,responsable,description) VALUES ('laverie','kalanna26','Kannerezh – Laverie',7,NULL,NULL);
INSERT INTO postes (id,event_id,nom,couleur,responsable,description) VALUES ('photo','kalanna26','Luc''hskeudenner – Photographe',3,NULL,NULL);
INSERT INTO postes (id,event_id,nom,couleur,responsable,description) VALUES ('regie','kalanna26','Merer teknikel – Régie & accueil artistes',1,NULL,'Régisseur + accueil des artistes, gestion des repas, accès hébergement.');
INSERT INTO postes (id,event_id,nom,couleur,responsable,description) VALUES ('secours','kalanna26','Sikourer – Secouristes',5,NULL,'Équipe d''appui professionnelle (astreinte).');
INSERT INTO postes (id,event_id,nom,couleur,responsable,description) VALUES ('secu','kalanna26','Surentez – Sécurité',7,NULL,'Équipe d''appui ORIOS : surveillance des entrées, des abords et des flux.');
INSERT INTO postes (id,event_id,nom,couleur,responsable,description) VALUES ('soubenn','kalanna26','Soubenn ognon – Soupe à l''oignon',1,NULL,'Équipe autonome de 3 personnes, service de 3h à 4h15.');
INSERT INTO postes (id,event_id,nom,couleur,responsable,description) VALUES ('stal','kalanna26','Stal – Boutique',6,NULL,NULL);
INSERT INTO postes (id,event_id,nom,couleur,responsable,description) VALUES ('tavarn','kalanna26','Tavarn – Bar',0,NULL,NULL);
INSERT INTO postes (id,event_id,nom,couleur,responsable,description) VALUES ('video','kalanna26','Filmaozer – Vidéo',3,NULL,NULL);
INSERT INTO creneaux (id,event_id,poste_id,jour,debut,fin,besoin,note) VALUES ('i1','kalanna26','inst','2026-12-29','09:00','18:00',6,'Horaires à préciser');
INSERT INTO creneaux (id,event_id,poste_id,jour,debut,fin,besoin,note) VALUES ('i2','kalanna26','inst','2026-12-30','10:00','19:00',14,'Tables, éclairage, matériel, déco (20 personnes minimum sur la journée avec l''équipe krampouezh)');
INSERT INTO creneaux (id,event_id,poste_id,jour,debut,fin,besoin,note) VALUES ('i3','kalanna26','kramp-prep','2026-12-30','10:00','19:00',4,'Préparation du stand krampouezh');
INSERT INTO creneaux (id,event_id,poste_id,jour,debut,fin,besoin,note) VALUES ('i4','kalanna26','kramp-prep','2026-12-30','14:00','18:00',3,'Ingrédients à Quimperlé, horaires à préciser');
INSERT INTO creneaux (id,event_id,poste_id,jour,debut,fin,besoin,note) VALUES ('b3','kalanna26','billet','2026-12-31','01:00','05:00',2,'Caisse crêpes/gâteaux');
INSERT INTO creneaux (id,event_id,poste_id,jour,debut,fin,besoin,note) VALUES ('b1','kalanna26','billet','2026-12-31','19:45','23:00',9,'1 resp. + 2 caisse + 6 contrôle');
INSERT INTO creneaux (id,event_id,poste_id,jour,debut,fin,besoin,note) VALUES ('b2','kalanna26','billet','2026-12-31','23:00','01:00',6,'2 caisse + 4 contrôle');
INSERT INTO creneaux (id,event_id,poste_id,jour,debut,fin,besoin,note) VALUES ('bo1','kalanna26','bod','2026-12-31','14:00','18:00',2,'Préparation des chambres, horaires à préciser');
INSERT INTO creneaux (id,event_id,poste_id,jour,debut,fin,besoin,note) VALUES ('e3','kalanna26','bugale','2026-12-31','02:00','05:00',2,'Jusqu''à la fin');
INSERT INTO creneaux (id,event_id,poste_id,jour,debut,fin,besoin,note) VALUES ('e1','kalanna26','bugale','2026-12-31','19:45','23:00',2,NULL);
INSERT INTO creneaux (id,event_id,poste_id,jour,debut,fin,besoin,note) VALUES ('e2','kalanna26','bugale','2026-12-31','23:00','02:00',2,NULL);
INSERT INTO creneaux (id,event_id,poste_id,jour,debut,fin,besoin,note) VALUES ('ca','kalanna26','caisses','2026-12-31','19:45','05:00',2,'Toute la soirée');
INSERT INTO creneaux (id,event_id,poste_id,jour,debut,fin,besoin,note) VALUES ('d1','kalanna26','degemer','2026-12-31','17:00','21:00',1,NULL);
INSERT INTO creneaux (id,event_id,poste_id,jour,debut,fin,besoin,note) VALUES ('g3','kalanna26','gobel','2026-12-31','02:00','04:45',1,NULL);
INSERT INTO creneaux (id,event_id,poste_id,jour,debut,fin,besoin,note) VALUES ('g1','kalanna26','gobel','2026-12-31','19:45','23:00',1,NULL);
INSERT INTO creneaux (id,event_id,poste_id,jour,debut,fin,besoin,note) VALUES ('g2','kalanna26','gobel','2026-12-31','23:00','02:00',1,NULL);
INSERT INTO creneaux (id,event_id,poste_id,jour,debut,fin,besoin,note) VALUES ('v3','kalanna26','gwisk','2026-12-31','02:00','05:00',5,'Jusqu''à la fin');
INSERT INTO creneaux (id,event_id,poste_id,jour,debut,fin,besoin,note) VALUES ('v1','kalanna26','gwisk','2026-12-31','19:45','23:00',8,'2 stands');
INSERT INTO creneaux (id,event_id,poste_id,jour,debut,fin,besoin,note) VALUES ('v2','kalanna26','gwisk','2026-12-31','23:00','02:00',5,NULL);
INSERT INTO creneaux (id,event_id,poste_id,jour,debut,fin,besoin,note) VALUES ('i5','kalanna26','inst','2026-12-31','09:00','14:00',8,'À partir de 9h');
INSERT INTO creneaux (id,event_id,poste_id,jour,debut,fin,besoin,note) VALUES ('ke4','kalanna26','kramp-enc','2026-12-31','00:00','03:00',2,NULL);
INSERT INTO creneaux (id,event_id,poste_id,jour,debut,fin,besoin,note) VALUES ('ke2','kalanna26','kramp-enc','2026-12-31','18:00','21:00',2,NULL);
INSERT INTO creneaux (id,event_id,poste_id,jour,debut,fin,besoin,note) VALUES ('ke3','kalanna26','kramp-enc','2026-12-31','21:00','00:00',4,NULL);
INSERT INTO creneaux (id,event_id,poste_id,jour,debut,fin,besoin,note) VALUES ('kg4','kalanna26','kramp-garn','2026-12-31','00:00','03:00',4,'Et rangements');
INSERT INTO creneaux (id,event_id,poste_id,jour,debut,fin,besoin,note) VALUES ('kg2','kalanna26','kramp-garn','2026-12-31','18:00','21:00',8,NULL);
INSERT INTO creneaux (id,event_id,poste_id,jour,debut,fin,besoin,note) VALUES ('kg3','kalanna26','kramp-garn','2026-12-31','21:00','00:00',8,NULL);
INSERT INTO creneaux (id,event_id,poste_id,jour,debut,fin,besoin,note) VALUES ('kv4','kalanna26','kramp-rav','2026-12-31','00:00','03:00',1,NULL);
INSERT INTO creneaux (id,event_id,poste_id,jour,debut,fin,besoin,note) VALUES ('kv1','kalanna26','kramp-rav','2026-12-31','14:00','18:00',1,NULL);
INSERT INTO creneaux (id,event_id,poste_id,jour,debut,fin,besoin,note) VALUES ('kv2','kalanna26','kramp-rav','2026-12-31','18:00','21:00',1,NULL);
INSERT INTO creneaux (id,event_id,poste_id,jour,debut,fin,besoin,note) VALUES ('kv3','kalanna26','kramp-rav','2026-12-31','21:00','00:00',1,NULL);
INSERT INTO creneaux (id,event_id,poste_id,jour,debut,fin,besoin,note) VALUES ('kr','kalanna26','kramp-resp','2026-12-31','14:00','03:00',2,NULL);
INSERT INTO creneaux (id,event_id,poste_id,jour,debut,fin,besoin,note) VALUES ('kt1','kalanna26','kramp-tour','2026-12-31','14:00','18:00',8,NULL);
INSERT INTO creneaux (id,event_id,poste_id,jour,debut,fin,besoin,note) VALUES ('kt2','kalanna26','kramp-tour','2026-12-31','18:00','21:00',2,NULL);
INSERT INTO creneaux (id,event_id,poste_id,jour,debut,fin,besoin,note) VALUES ('kt3','kalanna26','kramp-tour','2026-12-31','21:00','00:00',2,NULL);
INSERT INTO creneaux (id,event_id,poste_id,jour,debut,fin,besoin,note) VALUES ('kw2','kalanna26','kramp-vais','2026-12-31','18:00','21:00',1,NULL);
INSERT INTO creneaux (id,event_id,poste_id,jour,debut,fin,besoin,note) VALUES ('kw3','kalanna26','kramp-vais','2026-12-31','21:00','00:00',1,NULL);
INSERT INTO creneaux (id,event_id,poste_id,jour,debut,fin,besoin,note) VALUES ('la1','kalanna26','laverie','2026-12-31','19:00','23:00',1,'Effectif à préciser');
INSERT INTO creneaux (id,event_id,poste_id,jour,debut,fin,besoin,note) VALUES ('la2','kalanna26','laverie','2026-12-31','23:00','05:00',1,'Effectif à préciser, jusqu''à la fin');
INSERT INTO creneaux (id,event_id,poste_id,jour,debut,fin,besoin,note) VALUES ('ph','kalanna26','photo','2026-12-31','19:00','04:15',1,'Soirée');
INSERT INTO creneaux (id,event_id,poste_id,jour,debut,fin,besoin,note) VALUES ('r3','kalanna26','regie','2026-12-31','00:00','05:00',1,'Jusqu''à la fin');
INSERT INTO creneaux (id,event_id,poste_id,jour,debut,fin,besoin,note) VALUES ('r1','kalanna26','regie','2026-12-31','14:00','20:00',4,'1 responsable + 3');
INSERT INTO creneaux (id,event_id,poste_id,jour,debut,fin,besoin,note) VALUES ('r2','kalanna26','regie','2026-12-31','20:00','00:00',2,NULL);
INSERT INTO creneaux (id,event_id,poste_id,jour,debut,fin,besoin,note) VALUES ('m2','kalanna26','secours','2026-12-31','00:00','05:00',2,'Jusqu''à la fin');
INSERT INTO creneaux (id,event_id,poste_id,jour,debut,fin,besoin,note) VALUES ('m1','kalanna26','secours','2026-12-31','20:00','00:00',2,NULL);
INSERT INTO creneaux (id,event_id,poste_id,jour,debut,fin,besoin,note) VALUES ('s2','kalanna26','secu','2026-12-31','00:00','05:00',2,'Jusqu''à la fin');
INSERT INTO creneaux (id,event_id,poste_id,jour,debut,fin,besoin,note) VALUES ('s1','kalanna26','secu','2026-12-31','20:00','00:00',2,NULL);
INSERT INTO creneaux (id,event_id,poste_id,jour,debut,fin,besoin,note) VALUES ('so','kalanna26','soubenn','2026-12-31','03:00','04:15',3,'Équipe autonome');
INSERT INTO creneaux (id,event_id,poste_id,jour,debut,fin,besoin,note) VALUES ('st1','kalanna26','stal','2026-12-31','19:45','23:00',1,NULL);
INSERT INTO creneaux (id,event_id,poste_id,jour,debut,fin,besoin,note) VALUES ('st2','kalanna26','stal','2026-12-31','23:00','02:00',1,NULL);
INSERT INTO creneaux (id,event_id,poste_id,jour,debut,fin,besoin,note) VALUES ('t3','kalanna26','tavarn','2026-12-31','02:00','04:45',8,'Fin du service bar 4h30–4h45');
INSERT INTO creneaux (id,event_id,poste_id,jour,debut,fin,besoin,note) VALUES ('t1','kalanna26','tavarn','2026-12-31','19:45','23:00',8,NULL);
INSERT INTO creneaux (id,event_id,poste_id,jour,debut,fin,besoin,note) VALUES ('t2','kalanna26','tavarn','2026-12-31','23:00','02:00',10,NULL);
INSERT INTO creneaux (id,event_id,poste_id,jour,debut,fin,besoin,note) VALUES ('vid','kalanna26','video','2026-12-31','19:00','04:15',1,'Soirée');
INSERT INTO creneaux (id,event_id,poste_id,jour,debut,fin,besoin,note) VALUES ('bo2','kalanna26','bod','2027-01-01','09:00','12:00',2,'Petit-déjeuner et ménage');
INSERT INTO creneaux (id,event_id,poste_id,jour,debut,fin,besoin,note) VALUES ('bo3','kalanna26','bod','2027-01-02','10:00','13:00',2,'Lavage du linge (28 draps…), horaires à préciser');
INSERT INTO creneaux (id,event_id,poste_id,jour,debut,fin,besoin,note) VALUES ('i6','kalanna26','inst','2027-01-02','09:00','19:00',18,'Rangement et nettoyage');
COMMIT;
